spring.application.name=evidence-management-system

#DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/evidence_db
spring.datasource.username=vini
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

#JWT
jwt.secret=your_super_secret_key_must_be_at_least_32_characters_long
jwt.expiration=86400000piration=${JWT_EXPIRATION}